<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.3.1 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Fri, 15 Jun 2012 14:08:36 +0100
 */

/* Servers configuration */
$i = 0;

/* Server: MySQL localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'MySQL localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '8080';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysql';
//$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'root';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '4fdb33be1b0248.40625686';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
